Fix: prevent accessing undefined data-file-id attribute
BWPanda/featherlight pull request #1
Opened 2017-09-20 13:26 UTC by olivier-pierre

2017-09-21 01:32 UTC, ghost requested changes

2017-09-21 01:32 UTC, BWPanda commented on js/featherlight.js
> +      if (img[0].hasAttribute('data-file-id')) {
In what situation would `img` be an array...? I can't replicate this.

2017-09-21 01:32 UTC, BWPanda commented on js/featherlight.js
> +        var captionAttr = settings.featherlight.files[key];
The only error I can produce is: `TypeError: settings.featherlight.files is undefined`.

2017-09-21 03:02 UTC, BWPanda commented
@olivier-pierre Can you please test the following re-factored code and let me know if that works for you instead? If so, I'll make a new PR and commit it.

``` js
$.featherlight.prototype.afterContent = function() {
  var captionAttr = false;
  var caption = false;
  var img = this.$currentTarget.find('img');

  // Get caption attribute.
  if (settings.featherlight.hasOwnProperty('files')) {
    if (typeof img.attr('data-file-id') !== 'undefined') {
      var key = 'id-' + img.attr('data-file-id');
      captionAttr = settings.featherlight.files[key];
    }
  }
  else {
    if (settings.featherlight.caption_attribute) {
      captionAttr = settings.featherlight.caption_attribute;
    }
  }

  // Get and set caption.
  if (captionAttr) {
    caption = img.attr(captionAttr);

    if (caption) {
      this.$instance.find('.featherlight-caption').remove();
      $('<div class="featherlight-caption">').text(caption).appendTo(this.$instance.find('.featherlight-content'));
    }
  }
};
```

2017-09-21 07:02 UTC, olivier-pierre commented
No more error with your refactored code, thanks !

Note that `img` is always an array/object. It's a jQuery element, and `img[0]` or `img.get(0)` is the html element, if I understand it correctly.

But it doesn't really matter, your refactored code works perfectly, at least in my case !

2017-09-22 00:31 UTC, BWPanda commented
I've made a separate branch with the new code: https://github.com/backdrop-contrib/featherlight/tree/fix_undefined_errors

I'll merge that soon if all goes well.

2017-09-22 00:31 UTC, closed without merging